// frontend/src/views/TaskScheduler.vue
<template>
  <div class="task-scheduler">
    <el-card class="header-card">
      <div class="header-content">
        <h2>定时任务管理</h2>
        <el-button type="primary" @click="showCreateDialog = true">
          <el-icon><Plus /></el-icon>
          创建任务
        </el-button>
      </div>
    </el-card>

    <!-- 筛选和搜索 -->
    <el-card class="filter-card">
      <el-form :model="filterForm" inline>
        <el-form-item label="任务类型">
          <el-select v-model="filterForm.taskType" placeholder="全部类型" clearable>
            <el-option label="全部" value="" />
            <el-option label="HTTP 请求" value="http_request" />
            <el-option label="Shell 命令" value="shell_command" />
            <el-option label="Rust 函数" value="rust_function" />
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="filterForm.status" placeholder="全部状态" clearable>
            <el-option label="全部" value="" />
            <el-option label="启用" value="enabled" />
            <el-option label="暂停" value="paused" />
            <el-option label="禁用" value="disabled" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="loadTasks">查询</el-button>
          <el-button @click="resetFilter">重置</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 任务列表 -->
    <el-card class="table-card">
      <el-table 
        :data="tasks" 
        v-loading="loading"
        stripe
        style="width: 100%"
      >
        <el-table-column prop="name" label="任务名称" min-width="150" />
        <el-table-column prop="task_type" label="类型" width="120">
          <template #default="{ row }">
            <el-tag :type="getTaskTypeColor(row.task_type)">
              {{ getTaskTypeName(row.task_type) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="schedule_type" label="调度类型" width="100">
          <template #default="{ row }">
            <el-tag size="small">{{ getScheduleTypeName(row.schedule_type) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getStatusColor(row.status)">
              {{ getStatusName(row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="next_run_time" label="下次执行" width="180">
          <template #default="{ row }">
            <span v-if="row.next_run_time">
              {{ formatDateTime(row.next_run_time) }}
            </span>
            <span v-else class="text-gray-400">-</span>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="创建时间" width="180">
          <template #default="{ row }">
            {{ formatDateTime(row.created_at) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button-group size="small">
              <el-button @click="runTask(row)" :disabled="row.status !== 'enabled'">
                <el-icon><VideoPlay /></el-icon>
              </el-button>
              <el-button @click="editTask(row)">
                <el-icon><Edit /></el-icon>
              </el-button>
              <el-button 
                v-if="row.status === 'enabled'" 
                @click="pauseTask(row)"
                type="warning"
              >
                <el-icon><VideoPause /></el-icon>
              </el-button>
              <el-button 
                v-else-if="row.status === 'paused'" 
                @click="resumeTask(row)"
                type="success"
              >
                <el-icon><VideoPlay /></el-icon>
              </el-button>
              <el-button @click="deleteTask(row)" type="danger">
                <el-icon><Delete /></el-icon>
              </el-button>
            </el-button-group>
          </template>
        </el-table-column>
      </el-table>

      <!-- 分页 -->
      <div class="pagination-container">
        <el-pagination
          v-model:current-page="pagination.page"
          v-model:page-size="pagination.pageSize"
          :page-sizes="[10, 20, 50, 100]"
          :total="pagination.total"
          layout="total, sizes, prev, pager, next, jumper"
          @size-change="loadTasks"
          @current-change="loadTasks"
        />
      </div>
    </el-card>

    <!-- 创建/编辑任务对话框 -->
    <TaskDialog 
      v-model="showCreateDialog"
      :task="currentTask"
      @saved="onTaskSaved"
    />

    <!-- 执行记录对话框 -->
    <ExecutionDialog 
      v-model="showExecutionDialog"
      :task-id="currentTaskId"
    />
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Edit, Delete, VideoPlay, VideoPause } from '@element-plus/icons-vue'
import TaskDialog from './components/TaskDialog.vue'
import ExecutionDialog from './components/ExecutionDialog.vue'
import { taskApi } from '@/api/task'

// 响应式数据
const loading = ref(false)
const tasks = ref([])
const showCreateDialog = ref(false)
const showExecutionDialog = ref(false)
const currentTask = ref(null)
const currentTaskId = ref(null)

// 筛选表单
const filterForm = reactive({
  taskType: '',
  status: ''
})

// 分页
const pagination = reactive({
  page: 1,
  pageSize: 20,
  total: 0
})

// 任务类型映射
const taskTypeMap = {
  'http_request': 'HTTP 请求',
  'shell_command': 'Shell 命令', 
  'rust_function': 'Rust 函数'
}

const taskTypeColorMap = {
  'http_request': 'primary',
  'shell_command': 'success',
  'rust_function': 'warning'
}

// 调度类型映射
const scheduleTypeMap = {
  'cron': 'Cron',
  'interval': '间隔',
  'once': '一次'
}

// 状态映射
const statusMap = {
  'enabled': '启用',
  'paused': '暂停',
  'disabled': '禁用'
}

const statusColorMap = {
  'enabled': 'success',
  'paused': 'warning',
  'disabled': 'danger'
}

// 方法
const getTaskTypeName = (type) => taskTypeMap[type] || type
const getTaskTypeColor = (type) => taskTypeColorMap[type] || 'info'
const getScheduleTypeName = (type) => scheduleTypeMap[type] || type
const getStatusName = (status) => statusMap[status] || status
const getStatusColor = (status) => statusColorMap[status] || 'info'

const formatDateTime = (dateTime) => {
  if (!dateTime) return '-'
  return new Date(dateTime).toLocaleString('zh-CN')
}

// 加载任务列表
const loadTasks = async () => {
  loading.value = true
  try {
    const params = {
      page: pagination.page - 1, // API 使用 0 索引
      page_size: pagination.pageSize,
      task_type: filterForm.taskType || undefined,
      status: filterForm.status || undefined
    }
    
    const response = await taskApi.getTasks(params)
    tasks.value = response.tasks
    pagination.total = response.total
  } catch (error) {
    ElMessage.error('加载任务列表失败: ' + error.message)
  } finally {
    loading.value = false
  }
}

// 重置筛选
const resetFilter = () => {
  filterForm.taskType = ''
  filterForm.status = ''
  pagination.page = 1
  loadTasks()
}

// 创建任务
const createTask = () => {
  currentTask.value = null
  showCreateDialog.value = true
}

// 编辑任务
const editTask = (task) => {
  currentTask.value = { ...task }
  showCreateDialog.value = true
}

// 运行任务
const runTask = async (task) => {
  try {
    await ElMessageBox.confirm(`确定要立即执行任务 "${task.name}" 吗？`, '确认执行', {
      type: 'warning'
    })
    
    await taskApi.runTask(task.id)
    ElMessage.success('任务已开始执行')
    
    // 显示执行记录
    currentTaskId.value = task.id
    showExecutionDialog.value = true
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('执行任务失败: ' + error.message)
    }
  }
}

// 暂停任务
const pauseTask = async (task) => {
  try {
    await taskApi.pauseTask(task.id)
    ElMessage.success('任务已暂停')
    loadTasks()
  } catch (error) {
    ElMessage.error('暂停任务失败: ' + error.message)
  }
}

// 恢复任务
const resumeTask = async (task) => {
  try {
    await taskApi.resumeTask(task.id)
    ElMessage.success('任务已恢复')
    loadTasks()
  } catch (error) {
    ElMessage.error('恢复任务失败: ' + error.message)
  }
}

// 删除任务
const deleteTask = async (task) => {
  try {
    await ElMessageBox.confirm(`确定要删除任务 "${task.name}" 吗？此操作不可恢复！`, '确认删除', {
      type: 'warning'
    })
    
    await taskApi.deleteTask(task.id)
    ElMessage.success('任务已删除')
    loadTasks()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('删除任务失败: ' + error.message)
    }
  }
}

// 任务保存回调
const onTaskSaved = () => {
  showCreateDialog.value = false
  loadTasks()
}

// 初始化
onMounted(() => {
  loadTasks()
})
</script>

<style scoped>
.task-scheduler {
  padding: 20px;
}

.header-card {
  margin-bottom: 20px;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-content h2 {
  margin: 0;
  color: #303133;
}

.filter-card {
  margin-bottom: 20px;
}

.table-card {
  margin-bottom: 20px;
}

.pagination-container {
  display: flex;
  justify-content: center;
  margin-top: 20px;
}

.text-gray-400 {
  color: #9ca3af;
}

:deep(.el-button-group .el-button) {
  margin: 0;
}
</style>

// frontend/src/components/task-scheduler/TaskScheduler.tsx
'use client'

import React, { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/components/ui/toast'
import { Plus, Play, Pause, Edit, Trash2, RotateCcw } from 'lucide-react'
import { taskApi } from '@/api/task'
import TaskDialog from './TaskDialog'
import ExecutionDialog from './ExecutionDialog'

interface Task {
  id: number
  name: string
  description?: string
  task_type: string
  schedule_type: string
  status: string
  next_run_time?: string
  created_at: string
  updated_at: string
}

interface TaskFilter {
  task_type: string
  status: string
}

function getStatusBadge(status: string) {
  const variant = status === 'enabled' ? 'default' : 
                  status === 'paused' ? 'secondary' : 
                  status === 'disabled' ? 'destructive' : 'outline'
  return <Badge variant={variant as any}>{getStatusText(status)}</Badge>
}

function getStatusText(status: string) {
  const statusMap: Record<string, string> = {
    'enabled': '启用',
    'paused': '暂停', 
    'disabled': '禁用'
  }
  return statusMap[status] || status
}

function getTaskTypeText(type: string) {
  const typeMap: Record<string, string> = {
    'http_request': 'HTTP 请求',
    'shell_command': 'Shell 命令',
    'rust_function': 'Rust 函数'
  }
  return typeMap[type] || type
}

function getTaskTypeBadge(type: string) {
  const variant = type === 'http_request' ? 'default' :
                  type === 'shell_command' ? 'secondary' :
                  type === 'rust_function' ? 'outline' : 'outline'
  return <Badge variant={variant as any}>{getTaskTypeText(type)}</Badge>
}

function formatDateTime(dateTime?: string) {
  if (!dateTime) return '-'
  return new Date(dateTime).toLocaleString('zh-CN')
}

export default function TaskScheduler() {
  const queryClient = useQueryClient()
  const { showToast } = useToast()
  const [filter, setFilter] = useState<TaskFilter>({ task_type: '', status: '' })
  const [showCreateDialog, setShowCreateDialog] = useState(false)
  const [showExecutionDialog, setShowExecutionDialog] = useState(false)
  const [currentTask, setCurrentTask] = useState<Task | null>(null)
  const [currentTaskId, setCurrentTaskId] = useState<number | null>(null)

  // 获取任务列表
  const { data: tasksData, isLoading, refetch } = useQuery({
    queryKey: ['scheduled-tasks', filter],
    queryFn: () => taskApi.getTasks({
      task_type: filter.task_type || undefined,
      status: filter.status || undefined,
      page: 0,
      page_size: 100
    }),
    refetchInterval: 10000, // 每10秒刷新
  })

  const tasks = tasksData?.tasks || []

  // 运行任务
  const runMutation = useMutation({
    mutationFn: (taskId: number) => taskApi.runTask(taskId),
    onSuccess: (_, taskId) => {
      showToast('任务已开始执行', 'success')
      setCurrentTaskId(taskId)
      setShowExecutionDialog(true)
      refetch()
    },
    onError: (error: any) => {
      showToast(`执行失败: ${error.message}`, 'error')
    },
  })

  // 暂停任务
  const pauseMutation = useMutation({
    mutationFn: (taskId: number) => taskApi.pauseTask(taskId),
    onSuccess: () => {
      showToast('任务已暂停', 'success')
      refetch()
    },
    onError: (error: any) => {
      showToast(`暂停失败: ${error.message}`, 'error')
    },
  })

  // 恢复任务
  const resumeMutation = useMutation({
    mutationFn: (taskId: number) => taskApi.resumeTask(taskId),
    onSuccess: () => {
      showToast('任务已恢复', 'success')
      refetch()
    },
    onError: (error: any) => {
      showToast(`恢复失败: ${error.message}`, 'error')
    },
  })

  // 删除任务
  const deleteMutation = useMutation({
    mutationFn: (taskId: number) => taskApi.deleteTask(taskId),
    onSuccess: () => {
      showToast('任务已删除', 'success')
      refetch()
    },
    onError: (error: any) => {
      showToast(`删除失败: ${error.message}`, 'error')
    },
  })

  const handleCreateTask = () => {
    setCurrentTask(null)
    setShowCreateDialog(true)
  }

  const handleEditTask = (task: Task) => {
    setCurrentTask(task)
    setShowCreateDialog(true)
  }

  const handleRunTask = (task: Task) => {
    if (task.status !== 'enabled') {
      showToast('只能执行启用状态的任务', 'error')
      return
    }
    runMutation.mutate(task.id)
  }

  const handlePauseTask = (task: Task) => {
    pauseMutation.mutate(task.id)
  }

  const handleResumeTask = (task: Task) => {
    resumeMutation.mutate(task.id)
  }

  const handleDeleteTask = (task: Task) => {
    if (confirm(`确定要删除任务 "${task.name}" 吗？此操作不可恢复！`)) {
      deleteMutation.mutate(task.id)
    }
  }

  const handleTaskSaved = () => {
    setShowCreateDialog(false)
    refetch()
  }

  const resetFilter = () => {
    setFilter({ task_type: '', status: '' })
  }

  return (
    <div className="space-y-6">
      {/* 页面标题 */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold">定时任务管理</h1>
          <p className="text-muted-foreground">管理和监控定时任务的执行</p>
        </div>
        <Button onClick={handleCreateTask}>
          <Plus className="w-4 h-4 mr-2" />
          创建任务
        </Button>
      </div>

      {/* 筛选器 */}
      <Card>
        <CardHeader>
          <CardTitle>筛选条件</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4 items-end">
            <div className="space-y-2">
              <Label>任务类型</Label>
              <Select value={filter.task_type} onValueChange={(value) => setFilter(prev => ({ ...prev, task_type: value }))}>
                <SelectTrigger className="w-40">
                  <SelectValue placeholder="全部类型" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">全部类型</SelectItem>
                  <SelectItem value="http_request">HTTP 请求</SelectItem>
                  <SelectItem value="shell_command">Shell 命令</SelectItem>
                  <SelectItem value="rust_function">Rust 函数</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label>状态</Label>
              <Select value={filter.status} onValueChange={(value) => setFilter(prev => ({ ...prev, status: value }))}>
                <SelectTrigger className="w-32">
                  <SelectValue placeholder="全部状态" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">全部状态</SelectItem>
                  <SelectItem value="enabled">启用</SelectItem>
                  <SelectItem value="paused">暂停</SelectItem>
                  <SelectItem value="disabled">禁用</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Button variant="outline" onClick={resetFilter}>
              <RotateCcw className="w-4 h-4 mr-2" />
              重置
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* 任务列表 */}
      <Card>
        <CardHeader>
          <CardTitle>任务列表</CardTitle>
          <CardDescription>
            共 {tasks.length} 个任务
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>任务名称</TableHead>
                <TableHead>类型</TableHead>
                <TableHead>状态</TableHead>
                <TableHead>下次执行</TableHead>
                <TableHead>创建时间</TableHead>
                <TableHead>操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8">
                    加载中...
                  </TableCell>
                </TableRow>
              ) : tasks.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">
                    暂无任务数据
                  </TableCell>
                </TableRow>
              ) : (
                tasks.map((task) => (
                  <TableRow key={task.id}>
                    <TableCell className="font-medium">{task.name}</TableCell>
                    <TableCell>{getTaskTypeBadge(task.task_type)}</TableCell>
                    <TableCell>{getStatusBadge(task.status)}</TableCell>
                    <TableCell>{formatDateTime(task.next_run_time)}</TableCell>
                    <TableCell>{formatDateTime(task.created_at)}</TableCell>
                    <TableCell>
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleRunTask(task)}
                          disabled={task.status !== 'enabled' || runMutation.isPending}
                        >
                          <Play className="w-3 h-3" />
                        </Button>
                        
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleEditTask(task)}
                        >
                          <Edit className="w-3 h-3" />
                        </Button>
                        
                        {task.status === 'enabled' ? (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handlePauseTask(task)}
                            disabled={pauseMutation.isPending}
                          >
                            <Pause className="w-3 h-3" />
                          </Button>
                        ) : task.status === 'paused' ? (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleResumeTask(task)}
                            disabled={resumeMutation.isPending}
                          >
                            <Play className="w-3 h-3" />
                          </Button>
                        ) : null}
                        
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleDeleteTask(task)}
                          disabled={deleteMutation.isPending}
                        >
                          <Trash2 className="w-3 h-3" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* 对话框 */}
      <TaskDialog
        open={showCreateDialog}
        onOpenChange={setShowCreateDialog}
        task={currentTask}
        onSaved={handleTaskSaved}
      />

      <ExecutionDialog
        open={showExecutionDialog}
        onOpenChange={setShowExecutionDialog}
        taskId={currentTaskId}
      />
    </div>
  )
}
